# If not running interactively, don't do anything
[[ $- == *i* ]] || return 0

main() {
	set_options
	set_workstation_setup
	source_bashrc_dir # requires set_workstation_setup; keep high up
	editor_config
	npm_config
	ruby_config
	nix_config
	yabp_config
	go_config
	path_additions # requires homebrew_config
}

set_workstation_setup() {
	# Set the location workstation_setup (iCloud on MacOS; not the repo)
	# WORKSTATION_SETUP is used by sourced scripts
	if [[ "$OSTYPE" == "darwin"* ]]; then
		export ICLOUD_HOME="$HOME/Library/Mobile Documents/com~apple~CloudDocs"
		export WORKSTATION_SETUP="$ICLOUD_HOME/workstation_setup"
	elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
		# TODO
		pass
	fi
}

npm_config() {
	# npm -g installs to .local rather than /usr/local/
	if command -v npm &>/dev/null; then
		export npm_config_prefix="$HOME/.local"
	fi
}

source_bashrc_dir() {
	source "$WORKSTATION_SETUP/dotfiles/bashrc.d/bash_completion"
	source "$WORKSTATION_SETUP/dotfiles/bashrc.d/bash_functions"
	source "$WORKSTATION_SETUP/dotfiles/bashrc.d/bash_binds"
	if [[ "$OSTYPE" == "darwin"* ]]; then
		source "$WORKSTATION_SETUP/dotfiles/bashrc.d/bash_homebrew"
	fi
	source "$WORKSTATION_SETUP/dotfiles/bashrc.d/bash_aliases" # after bash_homebrew
}

editor_config() {
	if command -v nvim &>/dev/null; then
		export VISUAL=nvim
		export EDITOR="$VISUAL"
	fi
}

set_options() {

	# turn off bash history
	set +o history

	# update terminal size
	shopt -s checkwinsize

	# ** matches all files and zero or more directories and subdirectories
	shopt -s globstar

	# make less more friendly for non-text input files, see lesspipe(1)
	[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

	# append to the history file, don't overwrite it
	# shopt -s histappend

	# the maximum number of commands to remember
	# HISTSIZE=10000

	# the maximum number of lines in the history file
	# HISTFILESIZE=10000

	# don't put duplicate lines or lines starting with space in the history.
	# See bash(1) for more options
	HISTCONTROL=ignoreboth
}

go_config() {
	export GO111MODULE=on
	export GOPATH="$HOME/.go"
	export GOBIN="$GOPATH/bin"
}

nix_config() {
	if [[ -f "$HOME/.nix-profile/etc/profile.d/nix.sh" ]]; then
		source "$HOME/.nix-profile/etc/profile.d/nix.sh"
	fi
}

ruby_config() {
	if command -v ruby &>/dev/null; then
		export GEM_HOME="$HOME/.gems"
		export PATH="$HOME/.gems/bin:$PATH"

	fi
}

yabp_config() {

	YABP_DIRECTORY="$WORKSTATION_SETUP/wip/yabp"

	if [[ -d "$YABP_DIRECTORY" ]] && [[ -f "$YABP_DIRECTORY/core.sh" ]]; then
		source "$YABP_DIRECTORY/core.sh" "$YABP_DIRECTORY"
	fi
}

path_additions() {

	# If ~/.nix-profile exists, source it to activate Nix
	if [[ -L "$HOME/.nix-profile" ]]; then
		export PATH=$HOME/.nix-profile/bin:$PATH
	fi

	export PATH=$HOME/.bin:$GOBIN:$HOME/.local/bin:$PATH

}


main "$@"
