#!/usr/bin/env bash

PATH_TO_VTE_SH="/etc/profile.d/vte.sh"
MODULE_USER_TMP_DIRECTORY_ENABLE=true
MODULE_USER_TMP_DIRECTORY_PATH="/tmp/$(whoami)"
MODULE_RECENT_DIRECTORY_ENABLE=true
MODULE_RECENT_DIRECTORY_NUM_DIRECTORIES_TO_STORE=10
MODULE_TRUE_COLOR_ENABLE=true
