#!/usr/bin/env bash

if [[ "$OSTYPE" == "darwin"* ]]; then
	alias icloud='cd "$ICLOUD_HOME"'
	alias ssh-add='ssh-add --apple-use-keychain'
fi

# yabp: TODO
#alias g='cd "$(echo "$(realpath "$HOME"/Git/"$(ls "$HOME/Git" | fzf --tiebreak=end)")")" 2> /dev/null'
#alias q='cd "$(echo $(find . -type d ! -path "*/.*" | fzf --tiebreak=end))" 2> /dev/null'
# alias a='cd "$(echo "$(cat "/tmp/james/recent_dirs" | fzf --tiebreak=end)")" 2> /dev/null'
# alias b='exclude=$(mktemp); grep -v "$(echo "$(cat "/tmp/james/recent_dirs" | fzf --tiebreak=end)")" /tmp/james/recent_dirs > $exclude; cat $exclude > /tmp/james/recent_dirs'
# alias d='echo "$(pwd)" > /tmp/james/base_dir'


# git
alias gh='cd $(git rev-parse --show-toplevel)'
alias gl="git log --oneline"
alias gd='git diff'
alias gc='git commit'

# cd
alias w='cd "$HOME/Work.Git"'
alias d='cd "$HOME/Downloads"'
alias p='cd "$HOME/Personal.Git"'
alias o='cd "$HOME/Other.Git"'
alias workstation_setup='cd "$WORKSTATION_SETUP"'

# kubernetes
alias kc='kubectl'

# terraform
alias tf='terraform'

# gpg
alias gpg-lock="gpgconf --reload gpg-agent"

# command reminders
alias cr='cat "$WORKSTATION_SETUP"/command_reminders | fzf'
alias cre='nvim -c $ +put_ +startinsert "$WORKSTATION_SETUP"/command_reminders'

# sync workstation_setup iCloud to Git directory
alias workstation_setup_sync='rsync -av --delete --exclude "*.git*" "$WORKSTATION_SETUP" "$HOME/Personal.Git"'

# misc
alias t='cd $(mktemp -d); export TMP_DIR=$(pwd)'

# neovim
if command -v nvim &>/dev/null; then
	alias vi=nvim
	alias vim=nvim
fi
alias init.vim="nvim ~/.config/nvim/init.vim"

# yq
# json to yaml
alias jy="yq -P '.' "
# yaml to json
alias yj="yq -o=json '.' "

# Basics
alias start-ssh-agent='eval `ssh-agent` && ssh-add ~/.ssh/id_ed25519'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias rm='rm -i'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
	test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	alias ls='ls --color=auto'
	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
fi

# sf-sso
alias sso-claimable='aws-vault exec sf_sso -- sf-sso claimable'
alias sso-claim='aws-vault exec sf_sso -- sf-sso claim $(sso-claimable | tail -n +2 | grep -v -- "- " | fzf)'
alias sso-whoami='aws sts get-caller-identity'
alias sso-renew='aws-vault exec sf_sso -- sf-sso renew'
alias sso-reset='aws-vault exec sf_sso -- sf-sso reset'
alias sso-reset='aws-vault exec sf_sso -- sf-sso reset'
alias sso-status='aws-vault exec sf_sso -- sf-sso status'
alias sso-gen-config='aws-vault exec sf_sso -- sf-sso profile'
alias sso-login='aws-vault login --stdout $(aws-vault list --profiles | fzf) | pbcopy'
alias sso-login-default='aws-vault login $(aws-vault list --profiles | fzf) | pbcopy'
alias sso-exec='aws-vault exec $(aws-vault list --profiles | fzf)'
